# Generated by Django 3.2.3 on 2023-06-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Выберите единицу измерения ингредиента', max_length=10, verbose_name='Единица измерения')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='quantity',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='recipes.measurementunit', verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
