# Generated by Django 3.2.3 on 2023-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='RecipeIngredient',
            name='measurement_unit',
            field=models.CharField(default='1', help_text='Введите единицу измерения ингредиента', max_length=10, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
