# Generated by Django 3.2.3 on 2023-06-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_RecipeIngredient_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='RecipeIngredient',
            name='measurement_unit',
        ),
    ]
