# Generated by Django 3.2.3 on 2023-06-30 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230629_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default='1', help_text='Укажите количество ингредиента', verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент'),
            preserve_default=False,
        ),
    ]
