# Generated by Django 3.2.3 on 2023-06-18 11:19

import api.validators
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Укажите логин', max_length=150, unique=True, validators=[api.validators.validate_username], verbose_name='Логин пользователя')),
                ('first_name', models.CharField(blank=True, help_text='Укажите имя', max_length=150, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, help_text='Укажите фамилию', max_length=150, verbose_name='Фамилия пользователя')),
                ('email', models.EmailField(help_text='Укажите адрес электронной почты', max_length=255, unique=True, verbose_name='Адрес электронной почты')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=50, verbose_name='Статус пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='Выберите группы, к которым принадлежит пользователь.', related_name='users_in_group', to='auth.Group', verbose_name='Группы пользователя')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Выберите разрешения пользователя.', related_name='users_with_permission', to='auth.Permission', verbose_name='Разрешения пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('username',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_user'),
        ),
    ]
